name: 'PKP Github actions'
description: 'PKP CI/CD Pipeline'
inputs:
  pkp-application:
    description: 'PKP application'
    required: true
    default: 'ojs'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
strategy:
  fail-fast: false
matrix:
  php-versions: [ '8.1','8.2' ]
  dbs: [ 'pgsql']
env:
  DBUSERNAME: ojs-ci
  DBPASSWORD: ojs-ci
  DBNAME: ojs-ci
  DBHOST: 127.0.0.1
  DATABASEDUMP: database.sql.gz
  FILESDIR: files
  FILESDUMP: files.tar.gz
  CYPRESS_BASE_URL: http://127.0.0.1:8000
  CYPRESS_DBNAME: ojs-ci
  CYPRESS_DBUSERNAME: ojs-ci
  CYPRESS_DBPASSWORD: ojs-ci
  CYPRESS_DBHOST: 127.0.0.1
  CYPRESS_FILESDIR: files


runs:
  using: "composite"
  steps:
    - name: Install postgres server
      if: ${{matrix.dbs == 'pgsql'}}
      run: |
        sudo apt install postgresql postgresql-contrib
        sudo dpkg-reconfigure locales
        sudo sed -i -E 's\peer|scram-sha-256\trust\g' /etc/postgresql/14/main/pg_hba.conf
      shell: bash

    - name: Install  mysql server
      if: ${{matrix.dbs == 'mysql'}}
      run: |
        sudo apt install -q -y mysql-server mysql-client
        sudo service mysql start
        sudo mysqladmin -u root -p'root' password ''
      shell: bash

    - name: Install mariadb  server
      if: ${{matrix.dbs == 'mariadb'}}
      uses: ankane/setup-mariadb@v1
      with:
        mariadb-version: "10.11"

    - name: Setup PHP, extensions and composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php-versions}}
        extensions: bcmath, bz2, common, cli, curl, fpm, gd, intl, mbstring, mysql,mysqlnd, mysqli, opcache, pdo_mysql, pgsql, json,soap, xml, zip
        coverage: xdebug
      env:
        update: true

    - name: Install ${{inputs.pkp-application}}
      run: |
        git clone -b ${{ github.head_ref || github.ref_name }} https://github.com/$REPOSITORY ~/${{inputs.pkp-application}}
        cd ~/${{inputs.pkp-application}}
        git submodule update --init --recursive
      shell: bash
      env:
        REPOSITORY: withanage/ojs

    - name: Install composer dependencies
      run: |
        cd ~/${{inputs.pkp-application}}
        lib/pkp/tools/travis/install-composer-dependencies.sh
        npm i g -npm && npm i @vue/cli-service && npm i cypress && npm install && npm run build
      shell: bash
