on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validation
    steps:
      - uses: actions/checkout@v4
      
      - uses: xmlFlow/pkp-actions@v86
        with:
          pkp-repository: 'withanage/ojs'
          pkp-branch: 'issue#9214'