on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validation
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: xmlFlow/pkp-actions@v50+
        with:
          pkp-application: 'ojs'