on: [push, pull_request]
name: validate
jobs:
  upgrade:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
            php-version: 8.1
            database: pgsql
          
    name: validate
    steps:
      - name: Show files changed
      run: |
        echo ${{ toJSON(matrix.database) }} 
      
