on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validation
    steps:
      - uses: actions/checkout@v4
      
      - uses: xmlFlow/pkp-actions@v62-without-mkdir
        with:
          pkp-application: 'ojs'
          pkp-repository: 'withanage'
          pkp-branch: 'issue#9214'