on: [push]
name: validate
jobs:
  mx:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - php-version: 8.1
          database: pgsql
    name: validate
    steps:
      - name: test
        run: |
        echo ${{ toJSON(matrix.database) }} 
      
