on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validation
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: withanage/pkp-actions@{$1}
        with:
          application: 'ojs'