on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: pkp-integration
            
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.1','8.2' ]
        dbs: [ 'pgsql', 'mysql','mariadb']
    steps:
      - uses: actions/checkout@v4
      
      - uses: xmlFlow/pkp-actions@v135
        with:
          pkp-application: 'ojs'
          pkp-repository: 'withanage'
          pkp-branch: 'issue#9214'